using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;

public class DialogueManager : MonoBehaviour
{
    DialogueButton currentDialogueNode;
    [SerializeField] TextMeshProUGUI currentText;
    [SerializeField] Transform buttonsParent;
    [SerializeField] TextMeshProUGUI textArea;
    [SerializeField] GameObject UIParent;
    [SerializeField] Transform blackFrame;
    float timer;
    public bool isWorking;
    public static DialogueManager Instance{get;private set;}
    private void Awake() {
        Instance = this;
    }
    public void OpenUI()
    {
        UIParent.SetActive(true);
        isWorking = true;
    }
    public void CloseUI()
    {
        UIParent.SetActive(false);
    }
    bool isGenerated;
    private void Update() {
        if (isWorking)
        {
            timer += Time.deltaTime;
            if(timer >= 0.9f && !isGenerated)
             { 
                 // GenerateButtons();
                  isGenerated = true;
             }
        }
            
        else
        {
            if(timer<= 0.1f)
            {
                HideResponse();
            }
            timer -= Time.deltaTime;
        }
        timer = Mathf.Clamp(timer, 0, 1);
        blackFrame.transform.localScale = new Vector3(1,Mathf.Lerp(14,8.3f,timer),1);
    }
    void Hide()
    {
        isWorking = false;
    }
    public void HideInTime(float time)
    {
        Invoke("Hide", time);
    }

    public void SelectDialogue(DialogueButton dialogue)
    {
        currentDialogueNode = dialogue;
       // currentText.text = dialogue.response;
       // GenerateButtons();
       Invoke("DeleteButtons",0.5f);
       StartCoroutine(DialogueRoutine(1f));
    }
    void ShowLongText()
    {
        textArea.text = currentDialogueNode.longDescriptedText;
    }
    void ShowResponse()
    {
        textArea.text = currentDialogueNode.response;
    }
    void HideResponse()
    {
        textArea.text = "";
    }
    void DeleteButtons()
    {
        foreach (Transform item in buttonsParent)
        {
            Destroy(item.gameObject);
        }
    }
    IEnumerator DialogueRoutine(float waitTÄ°me)
    {
        yield return null;
        ShowLongText();
        yield return new WaitForSeconds(waitTÄ°me);
        ShowResponse();
        yield return new WaitForSeconds(.75f);
        //HideResponse();
        GenerateButtons();
        
    }

    void GenerateButtons()
    {
        
        foreach (var item in currentDialogueNode.children)
        {
            Instantiate(item,buttonsParent);
        }
    }
}
